language: csharp
solution: Skeleton.sln
install:
  - nuget restore Skeleton.sln
  - nuget install NUnit.ConsoleRunner -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Skeleton.sln
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Skeleton.Tests.Core/bin/Release/Skeleton.Tests.Core.dll
