
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  only: 
  - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# environment variables
environment: 
  AppVeyor: true

# enable service required for build/tests
services: 
  - mssql2014           

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform
platform: 
  - Any CPU

# build Configuration
configuration: 
  - Debug

before_build:
  - nuget restore 

build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"jej666:Skeleton" /n:"Skeleton" /v:"1.0.{build}" /d:sonar.host.url=https://sonarqube.com /d:sonar.login=21ad626032cd9eda6c8c6077790bad7d086a0a23
  - msbuild "Skeleton.sln"
  - MSBuild.SonarQube.Runner.exe end /d:sonar.login=21ad626032cd9eda6c8c6077790bad7d086a0a23
  
#---------------------------------#
#       test configuration        #
#---------------------------------#

before_test:
  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE TestDb" -d "master"
  
test:
  assemblies:
    only:
      - Skeleton.Tests.Core.dll
      - Skeleton.Tests.Infrastructure.dll
      - Skeleton.Tests.Web.dll
