
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  only: 
  - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# environment variables
environment: 
  AppVeyor: true
  SONARQUBE_REPO_TOKEN: 5c6c3a50986367578beecbb5d5926218c5252942
  COVERALLS_REPO_TOKEN:
    secure: hUKlb4xp2OhIGZ4VwMrZ9ok2UQAmDj+R6+Qay0UYnRtIIHwUVF9Ylb4Ov8/7WC1C

# enable service required for build/tests
services: 
  - mssql2014 
  
# build cache to preserve files/folders between builds 
cache:
  - packages -> **\packages.config

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform
platform: 
  - Any CPU

# build Configuration
configuration: 
  - Debug

before_build:
  - nuget restore 

#build:
#  project: Skeleton.sln
#  verbosity: minimal
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"Skeleton:master" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=SONARQUBE_REPO_TOKEN"
  - msbuild "Skeleton.sln"
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=SONARQUBE_REPO_TOKEN" 
 
#---------------------------------#
#       test configuration        #
#---------------------------------#

before_test:
  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE TestDb" -d "master"
  
test:
  assemblies:
    only:
      - Skeleton.Tests.Core.dll
      - Skeleton.Tests.Infrastructure.dll
    #  - Skeleton.Tests.Web.dll
      
after_test: 
   cmd: ./runTestForCoveralls.bat
