
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  only: 
  - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# environment variables
environment: 
  AppVeyor: true
  COVERALLS_REPO_TOKEN:
    secure: hUKlb4xp2OhIGZ4VwMrZ9ok2UQAmDj+R6+Qay0UYnRtIIHwUVF9Ylb4Ov8/7WC1C

# enable service required for build/tests
services: 
  - mssql2014 
  
# build cache to preserve files/folders between builds 
cache:
  - packages -> **\packages.config

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform
platform: 
  - Any CPU

# build Configuration
configuration: 
  - Debug

before_build:
  - nuget restore 

build:
  project: Skeleton.sln
  verbosity: minimal
  
#---------------------------------#
#       test configuration        #
#---------------------------------#

before_test:
  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE TestDb" -d "master"
  
test:
  assemblies:
    only:
      - Skeleton.Tests.Core.dll
      - Skeleton.Tests.Infrastructure.dll
    #  - Skeleton.Tests.Web.dll
      
after_test: 
   cmd: ./runTestForCoveralls.bat
