
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  only: 
  - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# environment variables
environment: 
  AppVeyor: true
  COVERALLS_REPO_TOKEN:
    secure: cNIM6h63k54BW7nyMal31txXrgb7ktWGVKpVA9BAp0oAZ6WvuMwSFUX2oZX5exFi

# enable service required for build/tests
services: 
  - mssql2014 
  
# build cache to preserve files/folders between builds 
cache:
  - packages -> **\packages.config

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform
platform: 
  - AnyCPU

# build Configuration
configuration: 
  - Debug

before_build:
  - nuget restore 

build:
  project: Skeleton.sln
  verbosity: minimal
  
#---------------------------------#
#       test configuration        #
#---------------------------------#

before_test:
  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE TestDb" -d "master"
  
test:
  assemblies:
    only:
      - Skeleton.Tests.Core.dll
      - Skeleton.Tests.Infrastructure.dll
      - Skeleton.Tests.Web.dll
      
after_test: 
    - packages\OpenCover.4.6.519\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.6.1\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  Skeleton.Tests.Infrastructure\bin\debug\Skeleton.Tests.Infrastrucuture.dll" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
