
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  only: 
  - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# environment variables
environment: 
  AppVeyor: true

# enable service required for build/tests
services: 
  - mssql2014           

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform
platform: 
  - Any CPU

# build Configuration
configuration: 
  - Release

before_build:
  - nuget restore

build:
  project: Skeleton.sln 
  verbosity: minimal

#---------------------------------#
#       test configuration       #
#---------------------------------#

before_test:
  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE TestDb" -d "master"
  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "if OBJECT_ID('CustomerCategory') is null
                    begin
	                    CREATE TABLE [dbo].[CustomerCategory] (
                        [CustomerCategoryId] INT        IDENTITY (1, 1) NOT NULL,
                        [Name]               NCHAR (50) NULL,
                        PRIMARY KEY CLUSTERED ([CustomerCategoryId] ASC)
                        )
                        set nocount on
	                    declare @i int
	                    set @i = 1
	                    while @i <= 10
	                    begin
		                    insert CustomerCategory ([Name]) values ('Category' + CAST(@i as varchar(2)))
		                    set @i = @i + 1
	                    end
                    end

                if OBJECT_ID('Customer') is null
                    begin
	                    CREATE TABLE [dbo].[Customer] (
                        [CustomerId]         INT           IDENTITY (1, 1) NOT NULL,
                        [Name]               NVARCHAR (50) NULL,
                        [CustomerCategoryId] INT           NULL,
                        PRIMARY KEY CLUSTERED ([CustomerId] ASC)
                        )
                        set nocount on
	                    declare @j int
	                    set @j = 1
	                    while @j <= 500
	                    begin
		                    insert Customer ([Name], [CustomerCategoryId]) values ('Customer' + CAST(@j as varchar(3)), ROUND( RAND() * 9 ,0) + 1)
		                    set @j = @j + 1
	                    end
                    end;" -d "master"
test:
  assemblies:
    only:
      - Skeleton.Tests.Core.dll
      - Skeleton.Tests.Infrastructure.dll
      - Skeleton.Tests.Web.dll
