version: 1.0.{build}
before_build:
  - nuget restore
build:
  project: Skeleton.sln 
  verbosity: minimal
platform:
  - Any CPU
configuration:
  - Release
test:
  categories:
    except:
      - Benchmarks
